### ISSUE TITLE
Error when calculation

### ISSUE THREAD

**Issue by RealNattawattHongthong** [WeloveMFP/Thai-tax-calculator-ver2566#10]
Hi!, @WeloveMFP , 
I just found the issue 
When I tried to calculate the tax it just error
Best Reguard!
Nattawatt

**Comment by WeloveMFP** [comment]
Code in your computer might be in the old version. Please delete deduct.py and download it again. If there is an error. Please let me know.

**Comment by WeloveMFP** [comment]
Hey @RealNattawattHongthong, I still can't find an error. Please capture the error part that happened to you. It would help me a lot.
Best regards 
WeloveMFP

**Comment by RealNattawattHongthong** [comment]
Hi!, @WeloveMFP 
Thanks for your information but my python is error
Best regards,
Nattawatt
