### ISSUE TITLE
Incorrect answer

### ISSUE THREAD

**Issue by WeloveMFP** [WeloveMFP/Thai-tax-calculator-ver2566#15]
Calculation part is fine (line203-231)
I think there is something wrong in deduction part(line1-201).

**Comment by RealNattawattHongthong** [comment]
> Calculation part is fine (line203-231) I think there is something wrong in deduction part(line1-201).

Which file html or Python?

**Comment by WeloveMFP** [comment]
@RealNattawattHongthong python file

**Comment by RealNattawattHongthong** [comment]
wait what... no way.

**Comment by RealNattawattHongthong** [comment]
@WeloveMFP Which part?

**Comment by WeloveMFP** [comment]
> @WeloveMFP Which part?

I have a skill issue in paper calculations
