### ISSUE TITLE
Error in calculate form

### ISSUE THREAD

**Issue by RealNattawattHongthong** [WeloveMFP/Thai-tax-calculator-ver2566#23]
So when calculate calculate in ``` reduct.html``` and it did not perform well.

**Comment by RealNattawattHongthong** [comment]
how do I need to solve

**Comment by WeloveMFP** [comment]
> how do I need to solve

We need to be sundar pichai Ai

**Comment by RealNattawattHongthong** [comment]
@WeloveMFP sure?
