### ISSUE TITLE
can't calculate over 5,000,000 

### ISSUE THREAD

**Issue by WeloveMFP** [WeloveMFP/Thai-tax-calculator-ver2566#7]
find_sum_income.py by @RealNattawattHongthong can't calculate tax over 5,000,000![ta1.jpg](https://github.com/WeloveMFP/Thai-tax-calculator-ver2566/assets/149069908/51689e4a-7bd1-42a2-9c44-d7ff80a863f3)

**Comment by WeloveMFP** [comment]
![20231109_135757.jpg](https://github.com/WeloveMFP/Thai-tax-calculator-ver2566/assets/149069908/7591d2bd-16fb-4295-824d-e40e7bc33ac2)

**Comment by WeloveMFP** [comment]
![20231109_134912.jpg](https://github.com/WeloveMFP/Thai-tax-calculator-ver2566/assets/149069908/5fd3aab8-6cc0-41e2-83cd-0d57fff7ae89)

**Comment by RealNattawattHongthong** [comment]
uhm

**Comment by RealNattawattHongthong** [comment]
try this!
def calculate_personal_income_tax(income):
    # Tax rate thresholds and rates for 2023 (Thai tax year)
    tax_thresholds = [0, 150000, 300000, 500000, 750000, 1000000, 2000000, 4000000, 5000000, 6000000]  # Updated thresholds
    tax_rates = [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.40]  # Updated rates

    # Calculate tax
    tax = 0
    remaining_income = income

    for i in range(1, len(tax_thresholds)):
        if remaining_income <= 0:
            break

        taxable_amount = min(remaining_income, tax_thresholds[i] - tax_thresholds[i - 1])
        tax += taxable_amount * tax_rates[i - 1]
        remaining_income -= taxable_amount

    return tax

def main():
    print("Welcome to the Thai Tax Calculator for the 2023 tax year")
    income = float(input("Please input your yearly income (THB): "))

    tax = calculate_personal_income_tax(income)
    print(f"Your estimated personal income tax for 2023 is: {tax:.2f} THB")

if __name__ == "__main__":
    main()

**Comment by WeloveMFP** [comment]
i set limit at 18,446,744,073,709,551,615
